Repository 2024-Circular-Reference/identity-verify-WAS, pull requests merged in 2024-02, with the labels that each got.

#3 [DevOps] CD 구축을 위한 Github Action 테스트
  .github/workflows/auto-test.yaml
  .github/workflows/deploy.yaml
  pull-from-hub.sh
  push-to-hub.sh
Labels: 🌩 DevOps

#5 [BE] 필요 API 구현 및 테스트, 개발을 위한 환경변수 설정
  .github/workflows/auto-test.yaml
  BE/holder/Dockerfile
  BE/holder/package-lock.json
  BE/holder/package.json
  BE/holder/src/app.controller.ts
  BE/holder/src/app.module.ts
  BE/holder/src/app.service.ts
  BE/holder/src/config/.test.env
  BE/holder/src/holder/holder-api.controller.ts
  BE/holder/src/holder/holder-api.module.ts
  BE/holder/src/holder/holder-api.service.ts
  BE/holder/src/holder/user-vc.dto.ts
  BE/holder/src/main.ts
  BE/holder/test/app.test.spec.ts
  BE/holder/test/jest-test.json
  BE/issuer/Dockerfile
  BE/issuer/package-lock.json
  BE/issuer/package.json
  BE/issuer/src/app.controller.ts
  BE/issuer/src/app.module.ts
  BE/issuer/src/app.service.ts
  BE/issuer/src/issuer/issuer-api.controller.ts
  BE/issuer/src/issuer/issuer-api.module.ts
  BE/issuer/src/issuer/issuer-api.service.ts
  BE/issuer/src/issuer/user-vc.dto.ts
  BE/issuer/src/main.ts
  BE/service/Dockerfile
  BE/service/package-lock.json
  BE/service/package.json
  BE/service/src/app.controller.ts
  BE/service/src/app.module.ts
  BE/service/src/app.service.ts
  BE/service/src/config/.test.env
  BE/service/src/main.ts
  BE/service/src/service/proof.dto.ts
  BE/service/src/service/service-api.controller.ts
  BE/service/src/service/service-api.module.ts
  BE/service/src/service/service-api.service.ts
  BE/service/test/app.test.spec.ts
  BE/verifier/Dockerfile
  BE/verifier/package-lock.json
  BE/verifier/package.json
  BE/verifier/src/app.controller.ts
  BE/verifier/src/app.module.ts
  BE/verifier/src/app.service.ts
  BE/verifier/src/main.ts
  BE/verifier/src/verifier/proof.dto.ts
  BE/verifier/src/verifier/verifier-api.controller.ts
  BE/verifier/src/verifier/verifier-api.module.ts
  BE/verifier/src/verifier/verifier-api.service.ts
Labels: 🌩 DevOps, 🖥 BE

#6 [BE] createUserVC API 구현 및 에러 처리 단일화
  BE/holder/src/dto/user-vc.dto.ts
  BE/holder/src/filter/custom-error.exception.ts
  BE/holder/src/filter/exception.filter.ts
  BE/holder/src/holder/holder-api.controller.ts
  BE/holder/src/holder/holder-api.service.ts
  BE/holder/src/main.ts
  BE/issuer/package-lock.json
  BE/issuer/package.json
  BE/issuer/src/app.module.ts
  BE/issuer/src/config/.test.env
  BE/issuer/src/dto/user-vc.dto.ts
  BE/issuer/src/filter/custom-error.exception.ts
  BE/issuer/src/filter/exception.filter.ts
  BE/issuer/src/issuer/issuer-api.controller.ts
  BE/issuer/src/issuer/issuer-api.module.ts
  BE/issuer/src/issuer/issuer-api.service.ts
  BE/issuer/src/issuer/user-vc.dto.ts
  BE/issuer/src/main.ts
  BE/issuer/src/types/types.ts
  BE/issuer/src/utils/utils.ts
  BE/service/package-lock.json
  BE/service/package.json
  BE/service/src/app.module.ts
  BE/service/src/config/.test.env
  BE/service/src/config/typeorm.config.ts
  BE/service/src/dto/proof.dto.ts
  BE/service/src/dto/user-vc.dto.ts
  BE/service/src/entity/holder_vc.entity.ts
  BE/service/src/filter/custom-error.exception.ts
  BE/service/src/filter/exception.filter.ts
  BE/service/src/main.ts
  BE/service/src/service/service-api.controller.ts
  BE/service/src/service/service-api.module.ts
  BE/service/src/service/service-api.service.ts
  BE/verifier/src/dto/proof.dto.ts
  BE/verifier/src/filter/custom-error.exception.ts
  BE/verifier/src/filter/exception.filter.ts
  BE/verifier/src/main.ts
  BE/verifier/src/verifier/verifier-api.controller.ts
Labels: 🖥 BE

#7 [SC] NEAR smart contract 구현
  SC/.gitignore
  SC/Cargo.lock
  SC/Cargo.toml
  SC/js_test/method.ts
  SC/js_test/package-lock.json
  SC/js_test/package.json
  SC/js_test/test_load_hashed_vc.js
  SC/readme.md
  SC/rust-toolchain.toml
  SC/rustfmt.toml
  SC/scripts/build.sh
  SC/scripts/deploy.sh
  SC/src/did_document.rs
  SC/src/lib.rs
  SC/src/test.rs
  SC/src/utils.rs
  SC/src/vc.rs
Labels: 📜 SC

#8 [BE][DB] DB 연결 후 student mock 데이터 작업 API 기능 구현
  BE/holder/src/config/.test.env
  BE/holder/src/holder/holder-api.service.ts
  BE/holder/src/main.ts
  BE/issuer/src/issuer/issuer-api.controller.ts
  BE/issuer/src/main.ts
  BE/service/src/config/typeorm.config.ts
  BE/service/src/dto/user-info.dto.ts
  BE/service/src/entity/student.entity.ts
  BE/service/src/main.ts
  BE/service/src/service/service-api.controller.ts
  BE/service/src/service/service-api.module.ts
  BE/service/src/service/service-api.service.ts
  BE/verifier/src/main.ts
  docker-compose.dev.yml
Labels: 🗄 DB
